### ISSUE TITLE
Explorer is empty

### ISSUE THREAD

**Issue by fmorency** [julienrbrt/simapp#28]
Hi @julienrbrt, I was exploring this project and wanted you to know that the explorer is empty, i.e., doesn't contain any data on the test chains.
Best

**Comment by julienrbrt** [comment]
Hey, thanks! I am migrating the servers and will re-start the nodes once this is done.
I will let you know here once it's done 👍🏾

**Comment by julienrbrt** [comment]
This should be fixed now: https://explorer.simapp.zone/simapp-next-1
